### ISSUE TITLE
header height is not appropriate

### ISSUE THREAD

**Issue by Xchos** [Koltzero/front-end-#1]
Use this stylesheets for each section instead of fixed height 1000px. It will look much better :)

![image](https://user-images.githubusercontent.com/2938356/27145056-7e81ebc8-5134-11e7-8ae9-e6de2e7afa6a.png)

**Comment by Koltzero** [comment]
Thanks for the tip :) I´ll make sure to use it 👍

**Comment by Xchos** [comment]
Dont use fixed height (property height). Always use min-height.

**Comment by Xchos** [comment]
solved
